//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtClubFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Event
    {
        
        public int EventID { get; set; }
        [Required(ErrorMessage ="Introducerea numelui este obligatorie")]
        public string Name { get; set; }
        [Required(ErrorMessage ="Introducerea locatiei este obligatorie")]
        public string Location { get; set; }
    }
}
